name: "${NAMESPACE}-adp"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${NAMESPACE}-adp"
    restart: always
    env_file:
      - .env
    ports:
      - "${ADP_PORT}:4000"
    volumes:
      - ./:/code

